### ISSUE TITLE
Possible issues with Ubuntu 20.04

### ISSUE THREAD

**Issue by mpearon** [PowerShell/GraphicalTools#100]
# Environment
## $PSVersionTable
Name|Value
--|--
PSVersion|7.1.0-preview.3
PSEdition|Core
GitCommitId|7.1.0-preview.3
OS|Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020
Platform|Unix
PSCompatibleVersions|1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion|2.3
SerializationVersion|1.1.0.1
WSManStackVersion|3.0
## Get-Module | Select-Object Name,Version
Name|Version
--|--
Microsoft.PowerShell.ConsoleGuiTools|0.4.1
Microsoft.PowerShell.GraphicalTools|0.2.0
Microsoft.PowerShell.Management|7.0.0.0
Microsoft.PowerShell.Utility|7.0.0.0
oh-my-posh|2.0.440
posh-git|1.0.0
PSReadLine|2.1.0

# Issue
## Issue Description
Out-GridView is non-functional on Ubuntu 20.04
## Expected Results
GUI opens and populates
## Actual Results
GUI does not open
## Reproduction Steps
1. Launch PowerShell
     ```sh
     pwsh -NoProfile
     ```
2. Test Out-GridView
     ```powershell
     Get-Process | Out-GridView
     ```
## Other Information
- No errors are echoed to the console
- Out-ConsoleGridView is fully functional

**Comment by corbob** [comment]
Can confirm, I'm able to reproduce this issue. Laptop was on 19.10, worked fine. Updated to 20.04 and now `Out-GridView` doesn't work 🤔

**Comment by TylerLeonhardt** [comment]
Thanks for opening this. At this time, I think we will be waiting to migrate GraphicalTools to [.NET MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) as we are not planning on investing resources on the Avalonia-based Out-GridView at this time.

I would recommend taking a look at ConsoleGuiTools as a replacement until we move further along with MAUI.

**Comment by mpearon** [comment]
@TylerLeonhardt - Understood!  Thank you for the information! :)

**Comment by TylerLeonhardt** [comment]
we can leave this open though :)

**Comment by TylerLeonhardt** [comment]
closing this in favor of #101
