### ISSUE TITLE
Add -Filter switch to set initial filter

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#109]
In the latest variant of the  "F7 for History" script @SteveL-MSFT used `Select-Object` `-like` to filter the history based on what was already on the command line. 

I think this would be much slicker if we could pass an initial text to the cmdlet to use as a filter. E.g.

```
ls | ocgv -Filter "foo"
```

Then the script could change to:

```powershell
...
    $history = Get-History | Sort-Object -Descending -Property Id | Select-Object CommandLine
    $selection = $history | Out-ConsoleGridView -Title "Select CommandLine from History" -OutputMode Single -Filter $line
...
```

Full script here: https://gist.github.com/tig/cbbeab7f53efd73e329afd6d4b838191

**Comment by TylerLeonhardt** [comment]
This is in

**Comment by tig** [comment]
When will you publish 0.6.0?

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/94476728-b68e7680-0185-11eb-8d6d-46c715e6a7e4.png)

**Comment by TylerLeonhardt** [comment]
https://www.powershellgallery.com/packages/Microsoft.PowerShell.ConsoleGuiTools/0.6.0
