### ISSUE TITLE
Colorization needs help for CodeSpaces

### ISSUE THREAD

**Issue by dfinke** [PowerShell/GraphicalTools#111]
Launched vsc from CodeSpaces and installed the `Microsoft.PowerShell.ConsoleGuiTools`.

Just the factory defaults for everything.

![image](https://user-images.githubusercontent.com/67258/94378860-8352d580-00fa-11eb-8b39-ddd37edfab90.png)

**Comment by TylerLeonhardt** [comment]
This is being tracked in gui.cs resolving as external.
