### ISSUE TITLE
OCGV: Columns don't always line up

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#112]
e.g.

```powershell
Get-PSProfile | ocgv
```

![image](https://user-images.githubusercontent.com/585482/94491143-80102600-019c-11eb-8618-b31fadcff8ab.png)

**Comment by TylerLeonhardt** [comment]
looks like the ellipses code is off by one...

**Comment by tig** [comment]
yea, I also don't like how much space is taken between the selection checks and first column. Waste.

FWIW, I'm working on changing Terminal.Gui to use just a single glyph to represent multi/single select instead of 3. This will also help.

**Comment by TylerLeonhardt** [comment]
dupe of #104 fix is in #113
