### ISSUE TITLE
OCGV: Does not seem to work in remote PSSession

### ISSUE THREAD

**Issue by lahell** [PowerShell/GraphicalTools#123]
Piping to `Out-ConsoleGridView` after `Enter-PSSession` produces an error and exits the PSSession. I have tried from Windows to MacOS and Windows to Ubuntu (WSL) using PowerShell 7.0.3 and Microsoft.PowerShell.ConsoleGuiTools 0.6.1. 

```
PS C:\Users\admin> $session = New-PSSession -HostName computer -UserName admin
admin@computer's password:
PS C:\Users\admin> Enter-PSSession -Session $session
[admin@computer]: PS /home/admin> Get-Process | Out-ConsoleGridView
There is an error processing data from the background process. Error reported: 'exadecimal value 0x1B, is an invalid character. Line 1, position 1..
PS C:\Users\admin>
```

Is it caused by ESC in `Dispose()`?

If it's not supposed to work in PSSession then perhaps check for the existence of `$PSSenderInfo` and handle it more gracefully without crashing out of the session.

**Comment by SteveL-MSFT** [comment]
I think for now, the cmdlet should check if it's remote and fail gracefully.  PowerShell remoting was designed to transport objects, so the text output for console rendering is confusing it.

**Comment by TylerLeonhardt** [comment]
> If it's not supposed to work in PSSession then perhaps check for the existence of $PSSenderInfo and handle it more gracefully without crashing out of the session.

@lahell would you like to try and contribute? This repo is participating in [hacktoberfest](https://hacktoberfest.digitalocean.com/) :)

**Comment by lahell** [comment]
@TylerLeonhardt, I gave it a shot, but as you will no doubt guess, I'm not a programmer.

I came up with this: https://github.com/lahell/GraphicalTools/commit/57e59688cb94ad182cf9505ccd4c96e51b668eec. It's not pretty, but seems to work.

What should I change?

**Comment by TylerLeonhardt** [comment]
Looks good :) the only thing I'd do is in the Dispose, instead of doing what you're doing now, just call: `_consoleGui?.Dispose()` which will do a null check

**Comment by lahell** [comment]
That would do a null check on _consoleGui right? As far as I can tell, the exit from remote session is caused by `Console.Write("\u001b[?1h");` in ConsoleGui.cs. What I was trying to do is only call Dispose if the cmdlet is not in a remote session. Is there a better way?

**Comment by lahell** [comment]
My first commit was overkill. Looks like `if (Console.IsInputRedirected)` is already handling it, but Dispose is crashing the remote session before the exception is displayed. This should be enough to fix it: https://github.com/lahell/GraphicalTools/commit/6bdb9d5eace2c9112179b86f195c77024cb2d4f5

**Comment by lahell** [comment]
Is this better? https://github.com/lahell/GraphicalTools/commit/e3ea9197f2976778b4bcc01a8a5132c0b329be02

**Comment by TylerLeonhardt** [comment]
Wait so, does it work over a remote session if you use that last commit?

**Comment by TylerLeonhardt** [comment]
It would be better if you sent a PR, easier for me to comment on :)

**Comment by lahell** [comment]
Sorry about the confusion. My last commit will not make OCGV work over a remote session. It will fail with a terminating exception, but the remote session will not be closed. Only the last commit in the PR is needed.
