### ISSUE TITLE
[WSL2] [Ubuntu 20.04] OCGV does not work

### ISSUE THREAD

**Issue by En3Tho** [PowerShell/GraphicalTools#133]
Does not work when using Ubuntu app terminal in Win10
![image](https://user-images.githubusercontent.com/37334640/105478720-96467280-5cb4-11eb-80f5-974ebd70dc18.png)

But works when calling ubuntu from other terminal and using pwsh there
![image](https://user-images.githubusercontent.com/37334640/105479241-49af6700-5cb5-11eb-968b-717d8b68f028.png)

**Comment by tig** [comment]
I'm confused. 

Can you please clarify what works and doesn't? I'll try to get Ubuntu 20.04 installed and test, but it may be a while.

**Comment by dgcom** [comment]
Had the same issue, turns out PowerShelll needs to be restarted after installing Microsoft.PowerShell.ConsoleGuiTools

**Comment by En3Tho** [comment]
> Had the same issue, turns out PowerShelll needs to be restarted after installing Microsoft.PowerShell.ConsoleGuiTools

This resolves the issue. Sorry for not trying out such a simple idea and thanks for your work! @tig
