### ISSUE TITLE
[Linux] [Ubuntu 20.04] Leaving OCGV causes mouse move to print characters to console

### ISSUE THREAD

**Issue by En3Tho** [PowerShell/GraphicalTools#134]
![image](https://user-images.githubusercontent.com/37334640/105478832-c0983000-5cb4-11eb-89d5-a1c25d9ca186.png)

**Comment by En3Tho** [comment]
@tig @TylerLeonhardt Can you please take a look?

**Comment by En3Tho** [comment]
I've updated pwsh to 7.1.1 manually (no such version in apt-get), problem remains

**Comment by tig** [comment]
see https://github.com/PowerShell/PowerShell/issues/12268

**Comment by DHowett** [comment]
This is a different thing, isn't it? Those characters look like xterm-encoded mouse positions. It looks like OCGV is leaving _mouse mode_ enabled.

The issue you linked, 12268, is about the encoding for the keyboard arrow keys (the up/down/left/right cluster.)

**Comment by En3Tho** [comment]
[Screenshot_2021-01-23-16-10-08-621_tech.ula.jpg](https://user-images.githubusercontent.com/37334640/105579148-b7cb5b00-5d95-11eb-87e1-ff243d2ffc9d.jpg)
No such behaviour on Android via UserLAnd (Ubuntu)

**Comment by TylerLeonhardt** [comment]
@En3Tho can you run this line and see if you still see the behavior?:

```
Write-Host "`e[?1003l"
```

This will turn of Mouse Tracking as described here:
https://www.xfree86.org/current/ctlseqs.html#Mouse%20Tracking

If this works for you, we can add emitting this here: 
https://github.com/PowerShell/GraphicalTools/blob/master/src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs#L329

**Comment by En3Tho** [comment]
@TylerLeonhardt It works. Thanks!

**Comment by TylerLeonhardt** [comment]
opened a small PR to fix this:
https://github.com/PowerShell/GraphicalTools/pull/135
