### ISSUE TITLE
Frameview Tabstop not working

### ISSUE THREAD

**Issue by shokkakhan** [PowerShell/GraphicalTools#136]
Using Microsoft.Powershell.ConsoleGuiTools:

I have two frames which both have $_.TabStop = $false.

Inside each frame, i have listview.

Both listviews also have tabstop set to false. 

No matter what I have tried, pressing tab switches from $Frame1 to $Frame2 and vice versa. The Tabstop is effective on both listviews. 

I put in a third frame to test, disabled tabstop, and it cannot be tabbed into. As soon as I add another control into the frame, the tabstop no longer works.

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
