### ISSUE TITLE
Runaway process on Ubuntu 20.4 displaying random characters upon exit.

### ISSUE THREAD

**Issue by cadayton** [PowerShell/GraphicalTools#139]
After displaying the grid view and exiting, random characters are being generated in the terminal session.

![image](https://user-images.githubusercontent.com/5587738/108508921-679ac800-7271-11eb-8589-4aae01de1f1a.png)

To reproduce, installed the BOTtum module.  [BOTtum](https://cadayton.keybase.pub/PSGallery/Modules/BOTtum/BOTtum.html)
Then execute the cmdlet, **Show-KBFileSystem "public" "cadayton"**

![image](https://user-images.githubusercontent.com/5587738/108510989-17713500-7274-11eb-870d-410e913784b5.png)

![image](https://user-images.githubusercontent.com/5587738/108510633-a0d43780-7273-11eb-8bf3-2c9e2078b4fb.png)

**Comment by scatenag** [comment]
Same here!

(..no Out-GridView and wreid Out-ConsoleGridView on Ubuntu right now :( )

**Comment by TylerLeonhardt** [comment]
This is fixed,it just needs to be released.

https://github.com/PowerShell/GraphicalTools/pull/135

cc @SteveL-MSFT

**Comment by cadayton** [comment]
Cool.  Thank you very much!!!

**Comment by tig** [comment]
@cadayton, can you please pull down PR #141 and verify this is fixed?

Thanks!

**Comment by cadayton** [comment]
On Ubuntu 20.4, I'm not running Windows Terminal.  How is an upgrade to Windows Terminal going to resolve the issue?

**Comment by cadayton** [comment]
On the Ubuntu system, I tried to update the Terminal.Gui package.  Unfortunately, I'm not up to speed enough on dotnet to figure out to get a newer Terminal.Gui nuget packages installed.

If you can provide a basic example of how to update the Terminal.Gui package, I'll be a able to test.  Otherwise, I'll need to wait until I find some time to learn how to speak dotnet.

**Comment by tig** [comment]
@TylerLeonhardt  or @SteveL-MSFT - Is there a way for you to do a build of GraphicalTools and publish a pre-release package on nuget?

**Comment by cadayton** [comment]
If can point me to the build documentation, I can build it.

**Comment by scatenag** [comment]
It seems to be fixed in PowerShell 7.1.3 :+1:

**Comment by tig** [comment]
Should be fixed by #141

**Comment by scatenag** [comment]
Yes!! It is fixed !

**Comment by tig** [comment]
@andschwa this can be closed.

**Comment by andschwa** [comment]
Awesome!
