### ISSUE TITLE
Get-Help with -ShowWindow opens underneath the terminal

### ISSUE THREAD

**Issue by nbros** [PowerShell/GraphicalTools#146]
When I invoke Get-Help with -ShowWindow, the help window opens, but underneath the Windows Terminal window instead of opening on top of it so that I can directly read the help page I requested.

eg with: `Get-Help Get-Item -ShowWindow`

![showWindow](https://user-images.githubusercontent.com/141089/156190164-c6daa20e-87c0-4393-8398-46ff1293bbdb.gif)

**Comment by tig** [comment]
This does not repo.

**Comment by SteveL-MSFT** [comment]
This is specific to graphical tools which is no longer supported in this repo
