### ISSUE TITLE
Feature-Request: have a button to select all currently filtered

### ISSUE THREAD

**Issue by MrFly72** [PowerShell/GraphicalTools#149]
It would be great to have a button to select all elements that are hit by the current filter.
EG. A list of movies is presented and the filter "Bruce" will filter all movies with Bruce Willis. 
If I press the wished button, all currently filtered will be selected.

**Comment by tig** [comment]
Good suggestion!

**Comment by tig** [comment]
This is a dupe of #120 which is fixed in #122.

@andschwa you can close this Issue.

**Comment by andschwa** [comment]
Thanks!!
