### ISSUE TITLE
Show-Command support

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/GraphicalTools#15]
This tracks support for the [Show-Command](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/show-command) cmdlet.

**Comment by corbob** [comment]
@TylerLeonhardt is there any requirement to close out #8 prior to looking at this one? Would working on this prior to #8 increase the complexity of that issue?

**Comment by TylerLeonhardt** [comment]
I think it would. The problem is, the GUI is very specific to Out-GridView, so the only way to do it today would be to create another GUI app for Show-Command which would crazily increase the size of this module.

cc @SteveL_MSFT

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
