### ISSUE TITLE
OCGV: Color changes and terminal becomes unreadable

### ISSUE THREAD

**Issue by saldroubi** [PowerShell/GraphicalTools#150]
I have this code basically in a loop so user can select an option, it gets performed and then menu appears again so he can pick another menu option to perform.

    $result = $menu | Out-ConsoleGridView -OutputMode Single -Title "Make a selection "

However, the color changes of background and foreground which makes the menu almost impossible to read.  Can this be fixed or is there a way to set the colors before calling Out-ConsoleGridView every time?

Thank you

**Comment by tig** [comment]
I've tried to repro this and can't quite figure out what you mean.

Could you perhaps post more code with a full example? 

What terminal / OS are you using? 

Thanks.

**Comment by tig** [comment]
@andschwa would you please edit this issue to previx the title with "OCGV: "? Thanks

**Comment by Tigger2014** [comment]
I have this happening too, Cant share code yet as it a lot of proprietary stuff but it once it starts it happens every time in that session

**Comment by tig** [comment]
This is no longer repo (or was fixed in #166).
