### ISSUE TITLE
Out-GridView does not work on linux

### ISSUE THREAD

**Issue by durdin85** [PowerShell/GraphicalTools#156]
Hi, I've recently discovered this project so I'd like to give it a try (Out-GridView from PowerShell.GraphicalTools) but on my machine it does not work (to be precise the terminal-based Outgridview works, but not the graphical based one).

When I try to do _anything | out-gridview_, no window appears and there's no sign of any new process either it just continues.
 
Manually running _"./.local/share/powershell/Modules/Microsoft.PowerShell.GraphicalTools/0.2.0/OutGridView.Gui/linux-x64/OutGridView.Gui"_ does also "nothing" --> The command just hangs waiting for input and I haven't figured out how to bring it alive or debug.

```
$PSVersiontable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Linux 5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Deb…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

 get-module Microsoft.PowerShell.GraphicalTools

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.2.0                 Microsoft.PowerShell.GraphicalTools {Out-GridView, ogv}

```

Could it be broken because I am running on wayland (not X11?) Or it's broken in general?

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/GraphicalTools/issues/156#issue-1276952302

`Show-ObjectTree` doesn't either, per https://github.com/orgs/PowerShell/discussions/21343#discussioncomment-8791255.
