### ISSUE TITLE
PSAnsiRenderingFileInfo causes display issues with Out-ConsoleGridView

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/GraphicalTools#159]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Filesystem provider output with `PSAnsiRenderingFileInfo` experiential feature enabled causes ANSI codes to be displayed when piped to `Out-ConsoleGridView`.

### Expected behavior

```console
No ANSI codes are displayed in `Out-ConsoleGridView`
```

### Actual behavior

```console
Name property has ANSI codes in Out-ConsoleGridView
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.4
PSEdition                      Core
GitCommitId                    7.3.0-preview.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                                 Version Prerelease Repository Description
----                                 ------- ---------- ---------- -----------
Microsoft.PowerShell.ConsoleGuiTools 0.6.2.0            PSGallery  Cross-platform Console Gui Tools for PowerShell
```

### Visuals

![image](https://user-images.githubusercontent.com/38873752/170298402-99156e1f-9be4-4ced-a1bc-f8a892c693f1.png)

**Comment by SteveL-MSFT** [comment]
This was fixed by https://github.com/PowerShell/GraphicalTools/pull/158
