### ISSUE TITLE
Release new GraphicalTools ...

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#165]
### Summary of the new feature / enhancement

Hey @andschwa & @SteveL-MSFT,

IMO we are at a good place to release a new release of GraphicalTools. 

If it were up to me, I'd merge all of the currently open PRs into `master` and do eet.

The release notes would read something like this:

Fixes:
* https://github.com/PowerShell/GraphicalTools/issues/151
* https://github.com/PowerShell/GraphicalTools/issues/150
* https://github.com/PowerShell/GraphicalTools/issues/121
* https://github.com/PowerShell/GraphicalTools/issues/120
* https://github.com/PowerShell/GraphicalTools/issues/116
* https://github.com/PowerShell/GraphicalTools/issues/87
* https://github.com/PowerShell/GraphicalTools/issues/44
* https://github.com/PowerShell/GraphicalTools/issues/139
* https://github.com/PowerShell/GraphicalTools/issues/159
* Removes building and distribution of `Out-GridView` and the other Avalonia-based components

Included PRs:
* https://github.com/PowerShell/GraphicalTools/pull/161
* https://github.com/PowerShell/GraphicalTools/pull/153
* https://github.com/PowerShell/GraphicalTools/pull/162
* https://github.com/PowerShell/GraphicalTools/pull/164
* https://github.com/PowerShell/GraphicalTools/pull/117
* https://github.com/PowerShell/GraphicalTools/pull/122
* https://github.com/PowerShell/GraphicalTools/pull/163
* https://github.com/PowerShell/GraphicalTools/pull/157
* https://github.com/PowerShell/GraphicalTools/pull/154

**Comment by SteveL-MSFT** [comment]
I believe @andschwa is planning a release this month

**Comment by andschwa** [comment]
Yes indeed!

**Comment by andschwa** [comment]
@tig can you close the correct issues and PRs that have been resolved via the merge of #166? Thank you! I am currently getting the build pipeline in place, should have a release out this week!

**Comment by tig** [comment]
Will do asap

**Comment by andschwa** [comment]
Thank you so much!!!

**Comment by MrFly72** [comment]
There are so cool new features in this release. 
It should be released and then there could be more work on additional features (like the jump to next item on select etc.)

**Comment by andschwa** [comment]
Working on it! It's a lot of infra work sadly. But it's close!

**Comment by MrFly72** [comment]
Maybe wait, as I have at least one big filed just before, that I think should be fixed before release, as it breaks functionality in my eyes.

**Comment by andschwa** [comment]
How breaking though? With this pipeline in place, once I can get it to work the first time, releases afterwords become easy as pie!

**Comment by andschwa** [comment]
(Also, the only way to get it to work is to test it...so expect a 0.7.2 as soon it works. We can do a 0.7.3 when your bugfix lands.)

**Comment by MrFly72** [comment]
I cannot fix it. Don't have invested any t8me on the code. I think @tig might have to look at it?
I was just pretty confused today after
Using filter, check items, using filter again, check some more and hit enter and to find out, only the last made it.

**Comment by andschwa** [comment]
@tig it's out! Going forward we can do a release _very_ easily now.
