### ISSUE TITLE
Clean up issues

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#169]
### Summary of the new feature / enhancement

Instead of prefixing OCGV Issues with "OCGV: ", we should have a label.

@andschwa any way I can get rights to be able to help you do all this?

**Comment by andschwa** [comment]
Just sent you an invite with triage permissions @tig! Thank you so much for your help. Release is coming out...shortly!

**Comment by andschwa** [comment]
Just created that label and added it to all the issues currently prefixed with `OCGV:`!
