### ISSUE TITLE
Show-Object cmdlet

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/GraphicalTools#178]
### Summary of the new feature / enhancement

As a user in the terminal I may have a variable that has lots of nested properties, therefore it would be good to get a UI similarly to what is available with the Show-Ast command in the ShowPSAst module written by @lzybkr as to be much more easily dig into it

Even if this is to begin with a Windows only thing, it would be a great help going forward for interactive troubleshooting of scripts / interactive workloads 

### Proposed technical implementation details (optional)

a cmdlet that pops out a GUI that allows you to drill into the depths of a variable

This could be released as a module and not built in if easier overall, but having it would be a good step

**Comment by SteveL-MSFT** [comment]
I think a `Show-Object` cmdlet would make more sense for the noun.  Terminal.GUI is supposed to have a new tree control that can be used.

**Comment by tig** [comment]
> I think a `Show-Object` cmdlet would make more sense for the noun. Terminal.GUI is supposed to have a new tree control that can be used.

Tee-hee. FYI, @tznind is a top-contributor to Terminal.Gui and the author of Terminal.Gui's Treeview control. He's also the author of Terminal.Gui's Table control which I am using for a rewrite of `Out-ConsoleGridView`.

**Comment by lzybkr** [comment]
Just a FYI - `Show-Ast` is based off of the `Show-Object` script in Windows PowerShell Cookbook, 3rd Edition by Lee Holmes.

**Comment by tig** [comment]
I do believe this is closed by #179
