### ISSUE TITLE
Question: how to check if installed?

### ISSUE THREAD

**Issue by dcnieho** [PowerShell/GraphicalTools#180]
### Summary of the new feature / enhancement

How to efficiently check whether `` is available?
I now use `Get-InstalledModule Microsoft.PowerShell.ConsoleGuiTools -ErrorAction SilentlyContinue` in my `$PROFILE`, but that takes about 1.5 s to execute.

**Comment by MrFly72** [comment]
Why not do a:
Get-Command Out-ConsoleGridView -ErrorAction SilentlyContinue
If it is Null, the Tool is not installed.

**Comment by tig** [comment]
Closing as answered.
