### ISSUE TITLE
Illegible output when run within Docker PowerShell Container

### ISSUE THREAD

**Issue by saldroubi** [PowerShell/GraphicalTools#183]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I have tried different PowerShell Containers such as ubuntu and alphine but Out-ConsoleGridView does not produce a legible output. Is there a workaround for this?  I want to run my application in a Docker PowerShell container but can't at the moment because it is using Out-ConsoleGridView. 

Command to run within Docker contain PS terminal:

Get-process | Out-ConsoleGridView

### Expected behavior

```console
Same behavior I see when I run it in my Mac OS X terminal window.
```

### Actual behavior

```console
Not legible output.
```

### Error details

```console
No error.  Not a readable screen.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.9
PSEdition                      Core
GitCommitId                    7.2.9
OS                             Linux 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.7.2

### Visuals

![out-consosuleGridView](https://user-images.githubusercontent.com/16247245/218162146-993e01ca-a172-44b5-90d6-cf53c286b247.jpg)

**Comment by tig** [comment]
Please see if https://github.com/gui-cs/Terminal.Gui/issues/2085 helps (`export TERM=xterm-256color`).

Can you test to see if Midnight Commander works properly in that environment?

**Comment by saldroubi** [comment]
Thank you.  Setting export TERM=xterm-256color does help the problem.  Now I able to see the list but when I select from the list the check mark is not showing.  Usually there is a "-" and when you select it turns it to a check mark. This way you know which ones you want to process.  In other words, I am supposed to see a check mark next to the item when I hit the space bar or use the mouse but it is not showing it on the screen.  In reality is selecting it because of the selected ones as shown in attached screenshot. 


Here is the command: 
Get-process | Out-ConsoleGridView -OutputMode Multiple -Title "Select one or more processes" 

 

![Out-ConsoleView_issue](https://user-images.githubusercontent.com/16247245/218285373-686ed1d8-32ee-48a8-8663-098ceb9ad261.jpg)

**Comment by tig** [comment]
Closing; see https://github.com/gui-cs/Terminal.Gui/issues/2341
