### ISSUE TITLE
OGV throws 'No usable version of libssl was found' on CentOS 9 Stream (RHEL 9)

### ISSUE THREAD

**Issue by brolifen** [PowerShell/GraphicalTools#191]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Install pwsh on a fresh CentOS 9 Stream:
sudo dnf install https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/powershell-7.3.4-1.rh.x86_64.rpm

Install the module
Install-Module Microsoft.PowerShell.GraphicalTools

### Expected behavior

```console
PS /> Get-Process | Out-GridView

shows ogv gui
```

### Actual behavior

```console
PS /> Get-Process | Out-GridView
PS /> No usable version of libssl was found
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.14.0-316.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri May 19 11:26:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

CentOS Stream 9

**Comment by SteveL-MSFT** [comment]
Avalonia no longer supported in this repo
