### ISSUE TITLE
OCGV leaves behind the bottom line of the view when closing

### ISSUE THREAD

**Issue by alexisspencer** [PowerShell/GraphicalTools#203]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. `Get-Process | Out-ConsoleGridView -OutputMode Single -Title "Test"`
2. Press ENTER or ESC

### Expected behavior

```console
Close OCGV window, all of the view is removed from the console
```

### Actual behavior

```console
While using the latest version of Out-ConsoleGridView, when closing the view (either by selecting an item or pressing ESC), OCGV leaves behind the very bottom line of the view - the bar at the bottom which shows "SPACE Select Item | ENTER Accept | ESC Close", which on a clean console, looks unpleasant as the scripts progress.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.7.3

### Visuals

<img width="1322" alt="image" src="https://github.com/PowerShell/GraphicalTools/assets/75229226/0f4fddaa-7d57-47df-82b2-ee053c6bb08c">

**Comment by tig** [comment]
Yes, this is a bug in Terminal.Gui that we've been struggling with. 

I'll link to the terminal.Gui issue asap.

**Comment by BDisp** [comment]
@alexisspencer which terminal you are using in the image?

**Comment by BDisp** [comment]
> @alexisspencer which terminal you are using in the image?

Forget I already reproduced it with `cmd`.

**Comment by tig** [comment]
I'm reopening this as my fix does not seem to actually work. See https://github.com/gui-cs/F7History/issues/13

**Comment by tig** [comment]
@andyleejordan and/or @SteveL-MSFT 👍 

Can you please point me at where PowerShell emits ANSI ESC sequences. I'm particularly interested in code where the behavior is different on Windows vs. Linux.
