### ISSUE TITLE
out-consolegridview clears the console history in Terminal

### ISSUE THREAD

**Issue by lexiismadd** [PowerShell/GraphicalTools#213]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When using out-consolegridview in Terminal, it clears all of the console history other than what was on the terminal window when out-consolegridview is called, meaning you cannot scroll back up past what was on the screen when out-consolegridview is called.
Unsure if this happens in regular PS Core, but it occurs in Terminal v1.17.11461.0 with ocgv 0.7.4.

### Expected behavior

```console
Out-ConsoleGridView is called.
User provides some form of input.
OCGV is closed
The console history can still be scrolled back up through (to the actual limit of the console history or what its set to)
```

### Actual behavior

```console
Out-ConsoleGridView is called.
User provides some form of input.
OCGV is closed.
Any console history not in the console window when OCGV is closed is cleared.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.7.4

**Comment by tig** [comment]
I can't reproduce this. Terminal.Gui used to have behaviors that caused this but that was fixed recently.

Can you please start Windows Terminal with the debug tap turned on and share the ANSI ESC codes that get sent when OCGV closes?

https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap#:~:text=To%20enable%20the%20debug%20tap%3A%201%20Enable%20debug,the%20input%20and%20output%20sent%20to%20the%20Terminal.

I'm looking to see if `ESC[0J`, `ESC[1J`, or `ESC[3J` is emitted.

**Comment by alexisspencer** [comment]
Sorry, i'm a bit confused where to add this setting in Windows Terminal:
`"debugFeatures": true,`

**Comment by tig** [comment]
> Sorry, i'm a bit confused where to add this setting in Windows Terminal: `"debugFeatures": true,`

Open WT's Settings. On the bottom of the window is:

<img width="261" alt="image" src="https://github.com/PowerShell/GraphicalTools/assets/585482/894e1bd3-3eb6-44a5-9696-9f2e705ae36d">

Click that. The .json settings file will open in you editor:

<img width="240" alt="image" src="https://github.com/PowerShell/GraphicalTools/assets/585482/a8d863ed-9622-4ff5-959e-e0ab8e34d466">

**Comment by alexisspencer** [comment]
Sure, here you go..
[https://wtools.io/paste-code/bOM0](url)

**Comment by tig** [comment]
[Terminal.Gui.zip](https://github.com/PowerShell/GraphicalTools/files/12314034/Terminal.Gui.zip)

Please:

Find where `Microsoft.PowerShell.ConsoleGuiTools` is installed:

```ps
$env:PSModulePath -split ';'
```

In that directory, find `Terminal.Gui.dll`:
<img width="843" alt="image" src="https://github.com/PowerShell/GraphicalTools/assets/585482/829689e5-6a90-44bd-93d2-0fc07046db4b">

Extract Terminal.Gui.dll from the attached zip file and copy it over the one in that directory (you may have to kill all pwsh instances first).

See if it fixes the problem. If it doesn't please capture the WT debug feed again and tell me if you see `1047l` or `1049l` here:

```
Close␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␛[K␛[69;222H␛[m␛[13;28;13;1;32;1_␛[13;28;13;0;32;1_␛[8;68;133t␛[?1003;1006l␛[?1047l
```

**Comment by alexisspencer** [comment]
Hi, no luck I'm afraid.  Those codes don't even appear...
Here's the capture again after the updated dll was added:
[https://pastes.io/7hw63g7ujz](https://pastes.io/7hw63g7ujz)

**Comment by tig** [comment]
Can you capture a gif of what you're doing?

I'm mighty confused.

**Comment by lexiismadd** [comment]
ty!
