### ISSUE TITLE
Get-ChildItem doesn't work either via -InputObject or via pipeline

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/GraphicalTools#22]
```powershell
Get-ChildItem | Out-Gridview
```
```
out-gridview : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At line:1 char:17
+ get-childitem | out-gridview
+                 ~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Out-GridView], ArgumentOutOfRangeException
+ FullyQualifiedErrorId : System.ArgumentOutOfRangeException,OutGridView.Cmdlet.OutGridViewCmdletCommand
```

**Comment by mrboring** [comment]
I have the same problem. However, if I select only files it works:

```PowerShell
Get-ChildItem -File | Out-Gridview
```
or just directories:
```PowerShell
Get-ChildItem -Directory | Out-Gridview
```


Maybe it's not handling a mix of types (file and folder). I did the same test on PowerShell 5.1 and it worked fine. I also noticed that on 5.1 only a small number of fields were output, whereas on 6.2 lots of fields were output.

**Comment by TylerLeonhardt** [comment]
Currently it doesn't handle mixed types at the moment. @jzeiders should have a fix for that in a PR tomorrow.

**Comment by golovini** [comment]
workaround: Get-ChildItem c:\users | select name, length | Out-GridView

**Comment by TylerLeonhardt** [comment]
mixed types are now supported.
