### ISSUE TITLE
Out-Gridview does not display simple arrays

### ISSUE THREAD

**Issue by ziabytes** [PowerShell/GraphicalTools#28]
Out-Gridview does not display simple arrays or simple lists

like 1 to 100

`1..300 | out-gridview`

would fail.

A new window would open but it would be blank in the content area no numbers.

While some may argue against supporting such a functionality, I will argue that say a long list of names being easily filtered visually via out-gridview  and passthru  was already a usecase before

**Comment by jzeiders** [comment]
Definitely agree, the functionality is included in PR #27

**Comment by TylerLeonhardt** [comment]
This is released now.
