### ISSUE TITLE
"-ShowWindow" support for Get-Help

### ISSUE THREAD

**Issue by mqmashwani** [PowerShell/GraphicalTools#29]
This tracks support for the [Get-Help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help?view=powershell-6) cmdlet.

This is a request for enhancing Get-Help via proxy command which adds support for the "-ShowWindow" parameter.

It would be great to have support for hypertext. Ability to launch the default browser for web link would be great. The ability to launch a separate window showing documentation for a referenced command or about_help topic would also be invaluable.

Even better would be a Show-Help command which implements a non-blocking version of Show-Command but just for help.

The greatest would be if the "-Online" switch rendered the online help page in the PowerShell graphical window.

**Comment by alexbuzzbee** [comment]
Personally, I prefer `-Online` opening the help in the default browser.

**Comment by yecril71pl** [comment]
> Personally, I prefer `-Online` opening the help in the default browser.

`-Online` does not work for `about_*`.

**Comment by yecril71pl** [comment]
Please make sure the new help window has a paging margin defined.

**Comment by SteveL-MSFT** [comment]
No longer relevant as we're focusing on console gui tools only
