### ISSUE TITLE
WSL - Unhandled Exception when executing Out-Gridview command

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/GraphicalTools#32]
**Description:**
In Windows Subsystem for Linux (WSL) the following exception occurs when executing the Out-Gridview command:
```
dir | select name | out-gridview
```
**Exception message:**
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'OutGridView.Application.AvaloniaAppRunner' threw an exception. ---> System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at OutGridView.Application.AvaloniaAppRunner.BuildAvaloniaApp() in D:\a\1\s\src\OutGridView.Gui\AvaloniaAppRunner.cs:line 34
   at OutGridView.Application.AvaloniaAppRunner..cctor() in D:\a\1\s\src\OutGridView.Gui\AvaloniaAppRunner.cs:line 31
   --- End of inner exception stack trace ---
   at OutGridView.Application.Program.Main(String[] args) in D:\a\1\s\src\OutGridView.Gui\Program.cs:line 26
```
**Environment:**

Windows 10:
WSL 1 (Windows Build 1903) and 2 (Windows 10 Insider  Build 18985) - Linux Ubuntu 18.04

PowerShell 7 Preview.4

Microsoft.PowerShell.GraphicalTools v 0.2.0

![OG_03_2019-09-23_11-47-36](https://user-images.githubusercontent.com/19892435/65445134-8ccaa300-ddff-11e9-9593-4f112c962b2b.png)

**Comment by TylerLeonhardt** [comment]
WSL will have to be special cased. It's the only scenario where we want the Windows code path to fire when we run within Linux.

Since WSL has no screen, this exception is expected. However, thanks to WSL being able to launch Winoows processes, we can take advantage of that to get this feature.

**Comment by SteveL-MSFT** [comment]
I've seen some blog posts (not from Msft) on enabling x-windows on WSL which could make this work, but this is really outside the scope of this module for now.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Yes! But it only works on WSL-1 and not for the insider edition. I think this is due to the fact that it uses a VM (at least is my understanding).

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad yeah, that makes sense since WSL-1 was going through the NT Kernel and effectively was a Windows app while WSL-2 is a VM.  I don't see this being supported in WSL-2.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

I just hope that in the future will work.  I'll keep praying for it!

:)

**Comment by MaximoTrinidad** [comment]
Please feel free to close this issue if the bottom line is that won't be supported.
Thanks!

**Comment by TylerLeonhardt** [comment]
The can be addressed as a feature. We just need to test for WSL and launch the Windows exe instead of the linux exe as that should work. Not sure if PassThru will work though.

**Comment by MaximoTrinidad** [comment]
@TylerLeonhardt 

As a Feature for WSL-2! That would be nice.

Keep in mind! It works in WSL-1 Windows 10 RTM with Windows Xserver. This is Great!!

![WSL-1_Outgridview_2019-10-03_10-55-48](https://user-images.githubusercontent.com/19892435/66138490-b5575780-e5cc-11e9-8e12-b80e5f49e81e.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
[The Windows Subsystem For Linux Preview](http://apps.microsoft.com/store/detail/9P9TQF7MRM4R) natively provides an X-server, so this remains important.

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
