### ISSUE TITLE
Out-GridView on macOS makes it difficult to select objects for the pipeline via -PassThru 

### ISSUE THREAD

**Issue by yobyot** [PowerShell/GraphicalTools#33]
Consider the following cmdlet entry:

`Get-AzSubscription | Where-Object -Property State -eq "Enabled" | Out-GridView -PassThru | Select-AzSubscription`

With `Out-GridView`, it's should very easy to graphically select which subscription object from the collection you wish to pass to `Select-AzSubscription`. The code works, but the UI needs to make it clear which row is selected.

For example, it's nearly impossible to tell which row is selected in this image: 
![ogvselection](https://user-images.githubusercontent.com/14332263/65975283-624e9a80-e43c-11e9-9af1-c204a5f90e30.png)
(Sorry, I had to obscure the GUIDs and names.) But the point can still be seen: one of these objects is selected but it's almost impossible to tell.

The colors in the macOS `OGV` UI need adjusting to clearly delineate which object is selected.

**Comment by corbob** [comment]
I don't think that's just a macOS thing. This is on Windows:

![image](https://user-images.githubusercontent.com/30301021/66012760-3e5f7900-e47d-11e9-902d-196c7720ef71.png)

I'll take a look at what is available.

**Comment by corbob** [comment]
Ok, so the theme is pretty much applied by this line: https://github.com/PowerShell/GraphicalTools/blob/master/src/OutGridView.Gui/App.xaml#L10
If I remove the line I get this: 
![image](https://user-images.githubusercontent.com/30301021/66014159-a6648e00-e482-11e9-966c-8219c66ef7e5.png)

and if I change the Light to Dark I get this (which is equally terrible): 
![image](https://user-images.githubusercontent.com/30301021/66014189-bda37b80-e482-11e9-8312-8dc4270b91b7.png)

Unfortunately I haven't been able to find anything in the Avalonia docs regarding styling things, or what options are available.

**Comment by SteveL-MSFT** [comment]
Perhaps we should make the row separator color (cyan-ish) lighter (or darker for dark theme).  Then the selected color needs more contrast.

**Comment by yobyot** [comment]
@SteveL-MSFT IMO, less is more. If my suggestions are of any value, I'd suggest that the whole pallet goes more towards "grey." That is (for a light theme), black text on white with very subtle row highlighting.

Here's a simple example from Excel. For a dark theme, you could probably reverse it. What I like about the Excel example here is that even when you select a row that's dark colored, the selection makes it even darker. And, of course, it's also easy to see when you've selected a light-colored row.


![2019-10-02_15-18-38](https://user-images.githubusercontent.com/14332263/66074933-648e2300-e528-11e9-8741-e605c76d93b6.png)

I think the real issue is that "candy color" pallets are hard to use but the dull, boring whites blacks and greys work across most devices. They are certainly less harsh on the eyes.

FWIW, I think Windows PowerShell was in the neighborhood. I know it looks "old" but it still looks good -- more professional and easier on the eyes.

![2019-10-02_15-25-45](https://user-images.githubusercontent.com/14332263/66075732-3873a180-e52a-11e9-9fc3-88bb97753f10.png)
 

Thanks!

**Comment by SteveL-MSFT** [comment]
@yobyot your feedback is definitely appreciated.  I would personally be fine with a more subdued grey tones for the display and a non-grey color to indicate selection.  I would suggest we trust that Excel has done their user research and we should just borrow their colors for presentation and selection.
