### ISSUE TITLE
Feature request: have a dark theme that picks up on OS theme

### ISSUE THREAD

**Issue by corbob** [PowerShell/GraphicalTools#38]
Avalonia provides a Dark Theme, but I'm not sure if it provides for detecting the OS mode.

If Avalonia can detect the OS mode (light vs dark), it would be really helpful to have the Gui components adopt a corresponding theme.

Possible technical solution:
* Detect the OS mode
* Modify the Dark theme provided by Avalonia to solve the contrast issue between selected rows and alternating rows.
* If OS is in dark mode, use dark theme
* If OS is in light mode, use light theme

Alternately: Provide a switch for the user to enable dark mode.

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
