### ISSUE TITLE
Import-Module causes warning on PowerShell 7 RC3

### ISSUE THREAD

**Issue by corbob** [PowerShell/GraphicalTools#44]
After running `Build.ps1` when the module is imported, and then does an `Out-GridView` on `Get-Process`. At the end of the build before this shows there appears to be a warning that couldn't write alias ogv as it is read only:

![image](https://user-images.githubusercontent.com/30301021/75842620-aea05c80-5d85-11ea-90d3-5337b257e880.png)

There's nothing in `$Error` hence why I think this is a warning instead of an error...

**Comment by TylerLeonhardt** [comment]
Yeah... we need to change the name of the cmdlet to something else now that the original ogv is back.
