### ISSUE TITLE
[Out-ConsoleGridView] Output should be left-aligned not right-aligned

### ISSUE THREAD

**Issue by alexandair** [PowerShell/GraphicalTools#50]
All these resource groups start with "demo", but you cannot see that for half of them.

![image](https://user-images.githubusercontent.com/3135708/76147447-92a9fd00-609c-11ea-9506-f8a7702f37ef.png)

**Comment by TylerLeonhardt** [comment]
I could see a mode in the menu that lets you switch from/to left-aligned to right-aligned. That way both are supported.

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT's work in #53 will greatly help with this.

**Comment by TylerLeonhardt** [comment]
Grab the latest version of this. It's a heck of a lot better.

**Comment by tig** [comment]
This can be closed now, I believe.
