### ISSUE TITLE
[Out-ConsoleGridView] Mouse doesn't work if Ubuntu (WSL) runs in Windows Terminal

### ISSUE THREAD

**Issue by alexandair** [PowerShell/GraphicalTools#51]
Mouse doesn't work if Ubuntu (WSL) runs in Windows Terminal.
It works if Ubuntu (WSL) runs in console host.

**Comment by TylerLeonhardt** [comment]
This is a dupe of https://github.com/migueldeicaza/gui.cs/issues/332 and is external to ConsoleGuiTools.
