### ISSUE TITLE
get-history | Out-ConsoleGridView with multi-line commands causes issues

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#58]
Start with:

```
$someJson = @'
{
   "foo" : true
}
'@
````

Then

    get-history | Out-ConsoleGridView

Results in something ugly like this:
    
![image](https://user-images.githubusercontent.com/585482/76385686-94372780-631f-11ea-9c93-7e9d89189090.png)

Powershell 7.0.

**Comment by TylerLeonhardt** [comment]
Looks like we just need to check if there are any newlines in the string here
https://github.com/PowerShell/GraphicalTools/blob/2aac3357e17e2f09b771cf4a49614fd02adcce96/src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs#L168-L176

and add an "..." just like the output of `Get-History` does.

```csharp
if (strings[i].Contains(Environment.NewLine)
{
    builder.Append(strings[i].Split(Environment.NewLine)[0]);
    builder.Append("...");
}
```

**Comment by TylerLeonhardt** [comment]
@tig any interest in contributing?

**Comment by tig** [comment]
Maybe. I have source cloned and can build ;-).

Noted Contribution Guide is 404: https://powershell.github.io/GraphicalTools/CONTRIBUTING.html

Also, can you point me at instructions for how to debug this using VS code?

I set a BP on the line you pointed to and hit Debug in Code but hit issues that I don't understand (noob at using VS Code to debug; I generally use VS Studio).

**Comment by TylerLeonhardt** [comment]
apologies for the 404! I'll get that fixed.

@tig take a look at [this section of the README for building.](https://github.com/PowerShell/GraphicalTools#development)

In order to debug VS Code, start a PowerShell process and import `ConsoleGuiTools`. Then in VS Code with the repo opened, go to the debug pane and select ".NET Core Attach". Then attach to the pwsh process that imported the module.

Once you run `Out-ConsoleGridView`, your breakpoint should get hit.

**Comment by tig** [comment]
How do I know which process is which?

![image](https://user-images.githubusercontent.com/585482/76440930-d68e5200-637b-11ea-9923-690e97514f7d.png)

**Comment by tig** [comment]
Nevermind. Found it `$pid`.

**Comment by tig** [comment]
Is there some way to not have to kill the Windows Terminal session hosting `pwsh` every build/debug cycle? I've tried just starting a `pwsh.exe` instance from the command line, but that doesn't seem to free up the loaded cmdlet. I have to kill Terminal.

**Comment by TylerLeonhardt** [comment]
You have to kill the pwsh.exe that imported the module because dlls can't be unloaded.

What I usually do is:

* open pwsh.exe
* in that pwsh.exe, run `pwsh` (thus nesting powershell)
* import the module and do debugging
* run `exit` to exit the nested PowerShell and run `pwsh` again

That way your window doesn't close... just the pwsh process within.

**Comment by tig** [comment]
Ready to do a PR. before I do, here's the strategy I took...

Your suggestion was to check for `Environment.Newline` and just do an ellipsis. 

First, in my example (not sure of others where there's multi-line commands) I'm seeing only `\n' and not `\r\n` as `Environment.NewLine` as defined for Windows.  So I am checking for `\n` only.

Second, just appending an ellipsis to the line is not very satisfyingly. In my example this would result in the command being displayed as:

    $someJson = @'

Instead, I'm doing this:

                strings[i] = strings[i].Replace("\n", @"\n");

                // If the string won't fit in the column, append an ellipsis.
                if (strings[i].Length > colWidths[i])
                {

Which lets the 'command too long' code deal gracefully with a command where newlines are encoded with the escape sequence.

Thus the output looks  like this:

![image](https://user-images.githubusercontent.com/585482/76459981-6cd17080-639a-11ea-9f6c-9916c2a8171d.png)

Cool?

**Comment by SteveL-MSFT** [comment]
I think following PowerShell syntax, it may make more sense to replace `\n` with `` `n``.  Otherwise, this seems like a good improvement.

**Comment by TylerLeonhardt** [comment]
I agree with @SteveL-MSFT

**Comment by tig** [comment]
Got it. Found https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7

**Comment by iSazonov** [comment]
"\r" and "\n" are not single control codes. Ideally we should escape output sting and mask all control characters and escape sequences.

**Comment by tig** [comment]
> "\r" and "\n" are not single control codes. Ideally we should escape output sting and mask all control characters and escape sequences.

I actually tried that (using `Regex.Escape`) and it didn't work well. That said, `Regex.Escape` uses `c/c++` style escaping, not `PowerShell` style. I vote leave it as-is for now as it fixes the UI-breaking problem caused by newlines.

**Comment by TylerLeonhardt** [comment]
Yes, we can be iterative here and fix the newline characters first since they will be seen a lot more than others
