### ISSUE TITLE
broken on Win 10 19577?

### ISSUE THREAD

**Issue by kort3x** [PowerShell/GraphicalTools#64]
I installed the preview for Win10 19577 which seems to break this module.

Out-ConsoleGridView: Index was outside the bounds of the array.

PSVersion                     7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19577
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by kort3x** [comment]
also:

https://github.com/PowerShell/GraphicalTools/issues/49#issuecomment-598756593

**Comment by kort3x** [comment]
nevermind - my bad

**Comment by TylerLeonhardt** [comment]
No worries!

**Comment by kort3x** [comment]
seems to be related to Terminal-Icons module

`dir | out-consolegridview` isn't working when Terminal-Icons has been imported.

Weird thing is that after the error is thrown once out-consolegridview isn't working at all anymore until I restart session/terminal. It just keeps throwing the same "bounds of array" error no matter what I pipe to it.

**Comment by kort3x** [comment]
![image](https://user-images.githubusercontent.com/13918530/76652397-d00ffe00-6566-11ea-8684-86ddbb806b0a.png)

**Comment by TylerLeonhardt** [comment]
Ahhh I've noticed this before... I don't think [gui.cs](https://github.com/migueldeicaza/gui.cs), that we depend on, handles non-ASCII characters well...
