### ISSUE TITLE
Mouse not working in Windows Terminal 0.10

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#69]
A new Windows Terminal build is out with console mouse support. 

It's not working with `out-consolegridview`. 

Note mouse support works fine in `cmd.exe` terminals.

Anyone know what needs to be implemented to support this?

**Comment by TylerLeonhardt** [comment]
You'll wanna voice these concerns in this issue:

https://github.com/migueldeicaza/gui.cs/issues/332

There's nothing we can do in this module since we depend on gui.cs for mouse support.
