### ISSUE TITLE
`Out-ConsoleGridView` should always have passthru

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/GraphicalTools#71]
Seems unnecessary to have to specify `-passthru`.  Instead, the user can just not select anything and nothing goes back to the pipeline.  I propose that pass thru is always enabled and remove the `-passthru` switch.  For new users, it more likely they wanted pass thru but now needs to rerun the pipeline and add that switch.

**Comment by iSazonov** [comment]
The same is true  for GUI version.

**Comment by corbob** [comment]
> 
> 
> The same is true for GUI version.

I think the biggest difference there would be that the console version is blocking execution and is expected to block execution. `Out-GridView` has an established norm that it does **not** block waiting for a return.

That's not to say that the GUI one shouldn't or couldn't be changed, just that there is a history to the GUI one that most people would expect it to behave that way.
