### ISSUE TITLE
 Out-ConsoleGridView - Jupyter Lab Host getting hung when using OCGV in Notebook

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/GraphicalTools#76]
As per @TylerLeonhardt request, I'm circling back to the issue I posted in .NET Interactive repo: 
https://github.com/dotnet/interactive/issues/311

This is impacting the Jupyter host kernel getting stuck with the only option to terminate the PowerShell console and start over Jupyter lab.

**Comment by TylerLeonhardt** [comment]
In the Jupyter environment, `[Console]::IsInputRedirected` is True... while in regular pwsh.exe (be it local or CloudShell) `[Console]::IsInputRedirected` is False. This seems like a good enough check.

We can add the check to the `BeginProcessing`:
https://github.com/PowerShell/GraphicalTools/blob/1b17e63103e86b9249f0fdde499929b31589908e/src/Microsoft.PowerShell.ConsoleGuiTools/OutConsoleGridviewCmdletCommand.cs#L66-L69

and do a `ThrowTerminatingError` saying "Not supported when input is redirected".
