### ISSUE TITLE
Refactor Gui project to be general purpose

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/GraphicalTools#8]
Right now, we have `OutGridView.Gui` which obviously only supplies the GUI side of Out-GridView. 

When we want to add other GUI tools like `Show-Command` and the likes we should refactor & rename `OutGridView.Gui` to `GraphicalTools.Gui` and figure out a way to signal `GraphicalTools.Gui` to show the `Show-Command` GUI instead of the `Out-GridView` GUI. This would allow us to reuse the Avalonia dlls that take up a lot of space.

**Comment by corbob** [comment]
I've started on this to help me wrap my head around how the function works.

I've broken it into a few steps of which I'm only on step 1:
1. Rename the OutGridView directories/files and references to the files themselves
2. Rename code references to OutGridView that are in the GraphicalTools.Gui and GraphicalTools.Model
3. Add a GuiComponent to ApplicationData that can be used to tell GraphicalTools what component has been called.

Once I'm done step 2 I'll open a Pull Request while debating step 3.

The WIP branch can be seen here: https://github.com/corbob/GraphicalTools/tree/issue-8

**Comment by corbob** [comment]
🤔 I think I missed a step between 2 and 3 where I qualify some of the models and views as being for OGV...

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
`.Gui` should be `.GUI`.

**Comment by peppekerstens** [comment]
I've made a proxy function for Out-Gridview to include OutConsoleGridview. Maybe include it in this module as a work-around in meantime?

https://gist.github.com/peppekerstens/b6553910fa316cfe9bdab2d73a3476a5

**Comment by peppekerstens** [comment]
no i would not mind at all :)

**Comment by SteveL-MSFT** [comment]
As this is for Avalonia and we're no longer investing in that, closing this issue.
