### ISSUE TITLE
apply button is on the left on non-Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/GraphicalTools#88]
![image](https://user-images.githubusercontent.com/2644648/79699997-b0e04c80-8247-11ea-8994-6a85560702a3.png)

maybe it's a good time to get rid of it since the Changed event is working.

cc @tig @SteveL-MSFT

**Comment by tig** [comment]
Fixed in https://github.com/PowerShell/GraphicalTools/pull/85

**Comment by tig** [comment]
(and FWIW, if you resized the terminal horizontally it would paint correctly; this is a bug in `gui.cs` where it does not paint controls positioned using `Dim` and `Pos` correctly initially).
