### ISSUE TITLE
Filters do not work right in out-consolegridview

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#89]
In the `/GraphicalTools` directory run:

```powershell
PS> ls | ocgv
```

## In the filter box, type a period (`.`).

Nothing happens. Expected: only files with periods in their names would show.

## Try escaping the period (assuming it's expecting a regex): `\.`. 

Get an error.

## Try an underscore (`_`)

Nothing happens. Expected: only files with underscores in their names would show (`CODE_OF_CONDUCT.md`).

## Try `.md`

Nothing happens. Hit space. Filter works.
Hit backspace. Cool.

etc...

**Comment by TylerLeonhardt** [comment]
Yes I have a feeling that when the Changed event started working, our logic was wrong.

**Comment by TylerLeonhardt** [comment]
fix out for this.
