### ISSUE TITLE
Support other release targets?

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/GraphicalTools#9]
Right now we support:

* `win-x64`
* `osx-x64`
* `linux-x64`

Should we support any others? Keep in mind, this increases the size of the package dramatically (around 100mb) because we have to ship an executable for that package.

**Comment by SteveL-MSFT** [comment]
No longer needed as part of Avalonia

**Comment by rokejulianlockhart** [comment]
This would probably have been better as a https://docs.github.com/discussions, @TylerLeonhardt
