### ISSUE TITLE
Out-GridView should remember window position

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#90]
I find it super annoying to have to resize it on my wide monitor. The default size it uses is crazy wide. 

![](https://i.imgur.com/BQ8yxn7.png)

**Comment by TylerLeonhardt** [comment]
Is this the _original_ out-grid view? If so, that needs to go in the PowerShell/PowerShell repo (and there might be an existing issue)

**Comment by tig** [comment]
I'm an idiot. Yes, I was running the old one. I just assumed `import-module` of the .dll that `ocgv` was in would have `ogv` in it too. I never ran it with `-verbose` so just assumed...

Much better default size. I still think it should remember size/position.

**Comment by TylerLeonhardt** [comment]
Should we close this then since it's about the old ogv?

**Comment by tig** [comment]
No, because I changed the title to be more specific to a valid feature request (that the new one doesn't save / restore it's window pos).

**Comment by iSazonov** [comment]
Is it possible on Unix? On Windows Registry is used to remember Windows size and position.

**Comment by tig** [comment]
You just need somewhere to store one each of:

    public enum FormWindowState
    {
        //
        // Summary:
        //     A default sized window.
        Normal = 0,
        //
        // Summary:
        //     A minimized window.
        Minimized = 1,
        //
        // Summary:
        //     A maximized window.
        Maximized = 2
    }

   Point

   Size
 
You do not need to use the registry. .NET Core provides a `SettingsService` that abstracts away where stuff is stored.

**Comment by iSazonov** [comment]
Can you point SettingsService API?

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
