### ISSUE TITLE
Out-ConsoleGridView does not exit on `ctrl-c`

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#91]
By default, `gui.cs` apps quit when the user hits `ctrl-c`. I personally am not a fan of this behavior because `ctrl-c` should be for copy (and `ctrl-v` for paste and `ctrl-x` for cut). However, it's the way it is right now.

I noted that without any apparent explicit code, `ocgv` does not exit on `ctrl-c`. Did someone do this intentionally or is it a byproduct of being a cmdlet?

**Comment by TylerLeonhardt** [comment]
It might be a byproduct of being a cmdlet. I wouldn't expect `ctrl-c` to quit `ocgv` either especially since we're explicit on `ESC` quitting.

**Comment by tig** [comment]
I verified with Miguel that exiting on ctrl-c is not the intended behavior for `gui.cs` apps. Thus I retract my question and am closing this issue because it is working correctly.
