### ISSUE TITLE
Putting results of ocgv on command line erases cursor

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#96]
I may be missing something, but this feels like a bug in `GraphicalTools`:

I want to define `F7` as "Show command history using ocgv":

```powershell
$parameters = @{
  Key = 'F7'
  BriefDescription = 'ShowHistoryOcgv'
  LongDescription = 'Show History using Out-ConsoleGridView'
  ScriptBlock = {
    param($key, $arg)   # The arguments are ignored in this example
    $history = Get-History -Count 100 | Out-ConsoleGridView -Title "Select Command" -OutputMode Single
    if (-Not [string]::IsNullOrWhiteSpace($history)){
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($history)
    }
  }
}
Set-PSReadLineKeyHandler @parameters
```

If I hit `F7` I get, as expected:
![image](https://user-images.githubusercontent.com/585482/80733729-4e9b0d80-8acb-11ea-8456-31f001539368.png)

I hit `ENTER` and get:
![image](https://user-images.githubusercontent.com/585482/80733759-5bb7fc80-8acb-11ea-81e4-8808545bcc34.png)

So, it put the item I selected (`ls`) on the command line, but nuked my prompt.

(I've tested this without  `posh-git` and `oh-my-posh` in-play and it reproduces, so it's not related to that).

This may be a `psreadline` issue? Or I may not have written `ShowHistoryOcgv` correctly. 

But I think it's related to `GraphicalTools` because If I change my `$history = ` above to:

    $history = Get-History -Count 1

It works as expected.

This works as expected as well:

    $history = Get-History -Count 100 | Out-GridView -Title "Select Command" -PassThru

Anyone have any insight?

**Comment by TylerLeonhardt** [comment]
@daxian-dbw do you have any insight here?

This is a really cool usecase of ocgv!

**Comment by tig** [comment]
> This is a really cool usecase of ocgv!

I agree. I've wanted a better history for a long time. 

If  you use this a lot, you'll see why I wanted `ENTER` to "select and exit". 

I still think we should make `-OutputMode Single` operate this way.

**Comment by daxian-dbw** [comment]
The console grid view is using the same console buffer and I guess it clears the buffer when exiting.
PSReadLine certainly doesn't expect the whole buffer got wiped out :)
Maybe the console grid view should be displayed on an alternate screen buffer, and it switches back to the main screen buffer when exiting.

**Comment by TylerLeonhardt** [comment]
@daxian-dbw 

> Maybe the console grid view should be displayed on an alternate screen buffer, and it switches back to the main screen buffer when exiting.

I was under the impression that this is how gui.cs works  - in an alternate screen buffer. Since that's the only way to control the whole screen. But maybe I'm wrong?

**Comment by daxian-dbw** [comment]
I don't know if gui.cs does that, but if the text on main screen buffer gets wiped out after `Out-ConsoleGridView`, then it's likely not using an alternate screen buffer.

**Comment by tig** [comment]
@migueldeicaza: can you comment on this?

**Comment by tig** [comment]
This here's the code:

https://github.com/migueldeicaza/gui.cs/blob/8b2624074174e4ab271cc176cc5f1801d13f561b/Terminal.Gui/Drivers/WindowsDriver.cs#L61

```csharp
public WindowsConsole ()
{
	InputHandle = GetStdHandle (STD_INPUT_HANDLE);
	OutputHandle = GetStdHandle (STD_OUTPUT_HANDLE);
	originalConsoleMode = ConsoleMode;
	var newConsoleMode = originalConsoleMode;
	newConsoleMode |= (uint)(ConsoleModes.EnableMouseInput | ConsoleModes.EnableExtendedFlags);
	newConsoleMode &= ~(uint)ConsoleModes.EnableQuickEditMode;
	ConsoleMode = newConsoleMode;
}

public bool WriteToConsole (CharInfo [] charInfoBuffer, Coord coords, SmallRect window)
{
	if (ScreenBuffer == IntPtr.Zero) {
		ScreenBuffer = CreateConsoleScreenBuffer (
			DesiredAccess.GenericRead | DesiredAccess.GenericWrite,
			ShareMode.FileShareRead | ShareMode.FileShareWrite,
			IntPtr.Zero,
			1,
			IntPtr.Zero
		);
		if (ScreenBuffer == INVALID_HANDLE_VALUE) {
			var err = Marshal.GetLastWin32Error ();

			if (err != 0)
				throw new System.ComponentModel.Win32Exception (err);
		}

		if (!SetConsoleActiveScreenBuffer (ScreenBuffer)) {
			var err = Marshal.GetLastWin32Error ();
			throw new System.ComponentModel.Win32Exception (err);
		}

		OriginalStdOutChars = new CharInfo [Console.WindowHeight * Console.WindowWidth];

		ReadConsoleOutput (OutputHandle, OriginalStdOutChars, coords, new Coord () { X = 0, Y = 0 }, ref window);
	}

	return WriteConsoleOutput (ScreenBuffer, charInfoBuffer, coords, new Coord () { X = window.Left, Y = window.Top }, ref window);
}

public void Cleanup ()
{
	ConsoleMode = originalConsoleMode;
	ContinueListeningForConsoleEvents = false;
	if (!SetConsoleActiveScreenBuffer (OutputHandle)) {
		var err = Marshal.GetLastWin32Error ();
		Console.WriteLine ("Error: {0}", err);
	}

	if (ScreenBuffer != IntPtr.Zero)
		CloseHandle (ScreenBuffer);

	ScreenBuffer = IntPtr.Zero;
}
```

Sure looks to me like `gui.cs` is using a second screen buffer, and restoring the original, to me.

**Comment by tig** [comment]
@daxian-dbw can you see anything the Windows driver for `gui.cs` could be doing, that it's not, that might fix this? I do believe all the relative code is above.

**Comment by daxian-dbw** [comment]
@tig what I meant about the alternate buffer is https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer
Maybe `Out-ConsoleGridView` should send the sequences `ESC[?1049h` to switch to a new alternate screen buffer before drawing anything, and switch back to the primary screen buffer by `ESC[?1049l` before it exists. That theoretically will preserve everything on the primary buffer.

**Comment by tig** [comment]
This helps. I think I have found the bug in `gui.cs` that is causing this based on your tip. 

I'll see if I an find time tonight to verify and fix.

Thanks!

**Comment by daxian-dbw** [comment]
@tig Can you share a little more on the potential bug? I'm curious :)

**Comment by tig** [comment]
Not 100% confident  this is the root of the problem yet, but `WindowsDriver.cs` does a `Console.Clear()` before it ends up calling `CreateConsoleScreenBuffer` as shown above. Thus, even thought the logic is there to allocate and use a different screen buffer, it clears the existing one.

**Comment by tig** [comment]
@daxian-dbw I have convinced myself the problem here is `gui.cs` is calling `Console.Clear()` before it creates and uses the alternative screen buffer (via `CreateConsoleScreenBuffer`). I found using the ANSI escape codes as you suggested makes no difference, but by simply commenting out the call to `Console.Clear()` fixes this issue.

Before I go further I need to confirm two things:

1. That, under the covers, emitting `ESC[?1049h` does the same thing as manually creating and using a screen buffer via `CreateConsoleScreenBuffer`. Can you confirm/deny that?
2. There was not some really good reason the `gui.cs` Windows Driver called `Console.Clear()`. I have a feeling it was just something whoever wrote it (@migueldeicaza?) did because it seemed like a good idea. If there was a good reason, I suspect it could be addressed in a different way.

**Comment by daxian-dbw** [comment]
> Can you confirm/deny that?

I cannot be sure about this, but I think it very likely using the `CreateConsoleScreenBuffer` and `SetConsoleActiveScreenBuffer` under the hood.

**Comment by tig** [comment]
Just verified the bad behavior described here does not repro on Linux. My little F7 script above works awesome under Ubuntu on WSL!

**Comment by tig** [comment]
This can be closed.
