### ISSUE TITLE
OCGV: Move "Set cursor key to application mode" fix to gui.cs

### ISSUE THREAD

**Issue by tig** [PowerShell/GraphicalTools#99]
https://github.com/PowerShell/GraphicalTools/blob/ad01f86e0fb93c606461ba60cb2b5aea4318a737/src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs#L295

I think this may be a bug that impacts all `gui.cs` apps and should be fixed there. However, I don't fully understand what the user impact of the bug described in these comments was and how setting the cursor key to application mode fixed it. Can you provide more detail?

As an aside, IIRC, `Dispose` for a Cmdlet is not actually guaranteed to get called until the CmdLet's module is unloaded. And that does NOT happen immediately after the Cmdlet is run. This `Dispose` gets called in `OutConsoleGridviewCmdletCommand`'s `Dispose`. In building `out-winprint` I discovered that I could not count on `Dispose` for timely cleanup and instead had to do stuff at the end of `EndProcessing`.  This is another reason I think this logic should be moved to `gui.cs` (unless I'm wrong about the fact the underlying bug impacts all `gui.cs` apps).

**Comment by TylerLeonhardt** [comment]
Yeah I needed to bring it over to gui.cs but it was easier to just "fix it here"

**Comment by tig** [comment]
Thanks. I'm confused though. Why is this needed? Why is it needed AT EXIT?

**Comment by tig** [comment]
https://github.com/PowerShell/GraphicalTools/issues/49

I bet this is a non-Windows issue, right? Because if I comment out that line I can't repro #49 on Windows...

**Comment by TylerLeonhardt** [comment]
Very possible.

**Comment by TylerLeonhardt** [comment]
btw if you ever need a cheap linux environment https://shell.azure.com is a great testing ground for OCGV behavior.

**Comment by tig** [comment]
Thanks. I actually use that (and WSL) here and there. The real problem is my dev skillz are barely adequate on Windows, and just getting started being able to enlist and build `GraphicalTools` on Linux is a bit much for me right now. I'm capable, it's just time.

**Comment by tig** [comment]
@TylerLeonhardt I got PS working on WSL and am sooo close. However, I can't figure out how to install dotnet core 3.1.102 on Ubuntu because the latest RPM installs 3.1.202. When I do `invoke-build build` I get this:

![image](https://user-images.githubusercontent.com/585482/81879525-466db400-9548-11ea-982b-2df92eaecce3.png)

If I change `global.json` to specify `3.1.202` I get this:

![image](https://user-images.githubusercontent.com/585482/81879584-72893500-9548-11ea-8bd8-45adc38fdddd.png)

Any pointers appreciated. Sorry for posting here, but figured it'd be the best way to ask you.

**Comment by TylerLeonhardt** [comment]
That second error is random and not our fault. Can you run it again?

**Comment by tig** [comment]
Different machine, same result. I've run it a dozen times. Has anyone else successfully built GraphicalTools on linux using `dotnetcore 3.1.202` by changing `global.json` as:

```json
{
    "sdk": {
        "version": "3.1.202"
    }
}
```

**Comment by TylerLeonhardt** [comment]
from your first screenshot it looks like you need to install zlib

**Comment by tig** [comment]
> from your first screenshot it looks like you need to install zlib

Nope, zlib is installed (via https://www.systutorials.com/how-to-install-the-zlib-library-in-ubuntu/). That was what I first tried. I believe this error is due to the fact I don't have donnetcore 3.1.102 installed. Because I can't easily install it. Because it's been superseded by 3.1.202.

![image](https://user-images.githubusercontent.com/585482/81983948-60170600-95f1-11ea-9f7f-284bd5a7475c.png)

I believe this because if I change `global.json` to require `3.1.202` the build actually progresses way past that point, but fails with that weird `C:\Microsoft\Xamarin\Nuget` error.

**Comment by TylerLeonhardt** [comment]
can you delete the `.dotnet` in GraphicalTools and try the build again?

**Comment by tig** [comment]
That was it. Thanks!

Woot!

![image](https://user-images.githubusercontent.com/585482/81988414-a328a780-95f8-11ea-921b-c7c7ebc431a3.png)

**Comment by TylerLeonhardt** [comment]
![](https://media.giphy.com/media/d3Kq5w84bzlBLVDO/source.gif)

**Comment by TylerLeonhardt** [comment]
You've got that issue in gui.cs open now - can we close this one?

**Comment by tig** [comment]
It's not fixed here until it's fixed there. Isn't it best practice to leave the issue open until there's a PR that fixes the issue (in this case, deletes the code from `Dispose`)? That PR can't happen until there's a build of `gui.cs` that def fixes the issue.

**Comment by tig** [comment]
@TylerLeonhardt Can you please comment out this fix and see if you can reproduce this? I cannot get this to reproduce on Linux under WSL. I've tried with both Windows Terminal and the WSL terminal. I don't have a mac to test on. I've double checked that I'm using my build of ocgv with that line commented out and that I did NOT fix it in `gui.cs` yet ;-).

I can't move this to `gui.cs` until I have a repro...

**Comment by TylerLeonhardt** [comment]
Yeah I can't repro anymore. That's interesting.

**Comment by tig** [comment]
This can be closed.
